name: Build and run tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
